title:            "@kavit"
url:              http://kavit900.github.io
permalink:        pretty
highlighter:      pygments
google_analytics: UA-72949752-1
timezone:         America/New_York
sass:
  sass_dir: assets
  style: :compressed
gems:
  - jemoji
  - jekyll-mentions
